language: node_js
node_js:
  - "8"
sudo: true

services:
  - postgresql
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
- npm run travis

cache:
  directories:
    - node_modules

install:
  - npm install

deploy:
  provider: script
  script: './deploy_dockerhub.sh'
  on:
    branch: master
