language: node_js
node_js:
  - "8"
sudo: false

script:
- npm run test-coverage
- npm run codecov

cache:
  directories:
    - node_modules

install:
  - npm install

deploy:
  provider: script
  script: './deploy_dockerhub.sh'
  on:
    branch: master
