language: node_js
node_js:
  - "8"
sudo: false

script:
- npm run test-coverage
- npm run codecov
- git checkout package-lock.json

services:
  - postgresql
  
before_script:
- psql -c 'create database travis_ci_test;' -U postgres

cache:
  directories:
    - node_modules

env:
- NODE_ENV=travis	
	
install:
  - npm install
    
deploy:
  provider: script
  script: './deploy_dockerhub.sh'
  on:
    branch: master
