GET http://localhost:8001/api/courses/summary
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImFkbWluIiwiaWF0IjoxNTU0NzE4Nzg2fQ.VkcfamfTd7i4nchXqKXoVa8Yl270oAaOmATRcuPxozQ