POST http://localhost:3004/api/students
Content-Type: application/json

{
  "student_id": "aaaabbbss",
  "first_name": "Jerkko",
  "last_name": "Opiskelija",
  "nickname": "Jerkkis",
  "phone": "+35844556677",
  "email": "arttis@ottis.fi",
  "learningopportunity_id": "TKT5-aa22",
  "course_name": "Kauttojurjestelmut",
  "period": 1,
  "year": 2022    
}