POST http://localhost:3003/api/students
Content-Type: application/json

{
  "student_id": "678645678",
  "first_name": "Herkko",
  "last_name": "Opiskelija",
  "nickname": "Herkkis",
  "phone": "+35844556677",
  "email": "arttis@ottis.fi",
  "learningopportunity_id": "TKT30008",
  "course_name": "Ohjelmistotuotanto 15",
  "period": 2,
  "year": 2019    
}