PUT http://localhost:8001/api/admins
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNTU0NzI5MDMwfQ.AVc5oC_clPTmev6oUkLD78fbx3ct440NoUy8CISDCeQ

{
    "oldPassword": "pass",
    "newPassword": "pass2"
}